version: '3.0'

services:
  auction-database:
    image: ghcr.io/phuuthanh2003/auction-database:latest
    ports:
      - "3306:3306"

  auction-api:
    image: ghcr.io/phuuthanh2003/auction-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - auction-database
